spring.application.name=tickets

# Banco PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Desabilita prepared statements — necessário para Supabase/PgBouncer (transaction pooling)
spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=dev

# Mostra as queries SQL no console
spring.jpa.show-sql=true

server.port=${PORT:8080}
server.shutdown=graceful
# Opcional: Tempo de espera para fechar (padrão é 30s)
spring.lifecycle.timeout-per-shutdown-phase=20s


# Formata o SQL para ficar legível (não ficar tudo em uma linha só)
spring.jpa.properties.hibernate.format_sql=true

# Mostra os valores reais que estão sendo inseridos (os "???" da query)
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# JWT Configuration
api.security.token.secret=${JWT_SECRET}

# Scalar/OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=false
