spring.application.name=tickets

# Banco PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

# Mostra as queries SQL no console
spring.jpa.show-sql=true

# JWT Configuration
api.security.token.secret=${JWT_SECRET}

# Scalar/OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=false
